version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "5006:5006"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "5005:5005"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=shareituser
      - SPRING_DATASOURCE_PASSWORD=shareit
#      - TZ=Europe/Moscow
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:14
    container_name: db
    volumes:
      - /shareit-postgresql-db
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareituser
      - POSTGRES_PASSWORD=shareit